sonarqube-check:
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  only:
    - main # or the name of your main branch
  
stages:
  - test
  - deploy

run_tests:
  stage: test
  image: python:3
  before_script:
    - 'pip install coverage'
    - 'pip install pytest'
  script:
    # - 'coverage run -m unittest discover -p "*_test.*"'
    - 'coverage run -m pytest test/'
  allow_failure: true

coverage report:
  stage: deploy
  extends: run_tests
  image: python:3
  when: always
  before_script:
    - 'pip install coverage'
    - 'coverage run -m unittest discover -p "*_test.py"'
    - 'coverage report --omit=test/__init__.py'
    - 'coverage xml'
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    when: always
    paths:
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: coverage.xml
